# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

ENV['RACK_ENV'] = 'test'
require File.expand_path("../../application", __FILE__)

RSpec.configure do |conf|
  conf.include Rack::Test::Methods
end

FactoryGirl.definition_file_paths = [
  File.join(File.dirname(__FILE__), 'factories')
]
FactoryGirl.find_definitions

def app
	Notes::App.instance
end

["support/*.rb" ].each do |path|
  Dir["#{File.dirname(__FILE__)}/#{path}"].each do |file|
    require file
  end
end
I18n.enforce_available_locales = false
